<?php
// module/Product/view/product/product/delete.phtml:

$title = 'Delete selected products';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete the selected products
    
    
</p>
<?php
$url = $this->url('product', array(
    'action' => 'delete_all',
    'products'     => $products,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $product->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>