<head>

    <script type="text/javascript">
		$(document).ready(function(){

    $('#selectCateg').change(function() {
       
        var select = $('#selectCateg').val();
      
		   if ( select) {
           $('#results').show();               
         $('#results').load('product/index?select=' + select);
         }
		});
    });


    </script>
</head>
<div id="results">
<?php
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$url = $this->url('product', array(
    'action' => 'deleteall',
));
?>


<form name="deleteall" action="<?php echo $url; ?>" method="get">

 <div class="navbar" >
 <div class="navbar-inner" >
 <div class="container" >

       
         <select id="selectCateg" style="width:200px;float:left;margin-top:7px" >
		  <option selected="true" value="">Choose Category</option>
         <?php foreach ($products as $product) : ?>
			<option value="<?php echo $product->id; ?>"> <?php echo $product->name; ?></option>
			  <?php endforeach;?>
			 
        </select>
        <a  class="btn btn-success" href="<?php echo $this->url('category', array('action'=>'add'));?>">Add new Category</a> 
		
		
		<div style="float:right">
		
	<a  class="btn btn-success" href="<?php echo $this->url('product', array('action'=>'add'));?>">Add new product</a> |
	  <input type="submit" name="deleteall" value="Delete all" class="btn btn-danger"/>
     </div>
	 </div>
	 </div>
	 </div>


<table class="table table-striped">
<tr>     
			 <th class="selector"><input id="all" type="checkbox" onClick="checkAll();" /></th>
			</th>
    <th>Name</th>
	<th>Number of items</th>
    <th>Action</th>
</tr>
<?php foreach ($categories as $product) : ?>
<tr>  
	<td class="selector"><input type="checkbox"  name="products[]"  value ="<?php echo $product->id;?>" /></td>
    <td><?php echo $this->escapeHtml($product->name);?></td>
    <td><?php echo $this->escapeHtml($product->number);?></td>
    
    
    <td>
        <a   class="btn btn-mini btn-warning" href="<?php echo $this->url('product',
            array('action'=>'edit', 'id' => $product->id));?>">Edit</a> |
        <a  class=" btn btn-mini btn-danger" href="<?php echo $this->url('product',
            array('action'=>'delete', 'id' => $product->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>


</table>

</form>

<script type="text/javascript" >
function checkAll() {
var all = document.getElementById("all");
	var inputs = document.getElementsByTagName('input');
	for(var i=0; i<inputs.length; i++){
	if(inputs[i].getAttribute('type')=='checkbox'){
		inputs[i].checked = all.checked? true:false
	}
	}
}	

	</script>
